const test=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.MEKEN_JSDOM_PATH||'jsdom');
const fs=require('node:fs');
const path=require('node:path');
const site=path.resolve(__dirname,'../site');
function boot(){const dom=new JSDOM(fs.readFileSync(path.join(site,'admin.html'),'utf8'),{url:'http://localhost/admin.html',runScripts:'outside-only'});const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(fs.readFileSync(path.join(site,'admin.js'),'utf8'));return{dom,w,d:w.document,click:s=>{const e=w.document.querySelector(s);assert.ok(e,'missing '+s);e.click()}}}
test('admin opens on operational overview and navigates all sections',()=>{const x=boot();assert.match(x.d.querySelector('#panel').textContent,/Капитал проектов/);for(const p of ['deals','investors','capital','governance']){x.click(`[data-panel="${p}"]`);assert.equal(x.d.querySelector('.side-link.active').dataset.panel,p)}x.dom.window.close()});
test('deal search, stage filter and detail status work',()=>{const x=boot();x.click('[data-panel="deals"]');const search=x.d.querySelector('#deal-search');search.value='арматура';search.dispatchEvent(new x.w.Event('input',{bubbles:true}));assert.equal(x.d.querySelectorAll('#deal-table tbody tr').length,1);x.click('[data-deal="MC-026"]');assert.equal(x.d.querySelector('#detail-dialog').open,true);const status=x.d.querySelector('#detail-stage');status.value='live';status.dispatchEvent(new x.w.Event('change',{bubbles:true}));assert.match(x.w.sessionStorage.getItem('meken-admin-deals'),/"stage":"live"/);x.dom.window.close()});
test('publication stays locked until every document is checked',()=>{const x=boot();x.click('[data-panel="governance"]');const card=x.d.querySelector('[data-gov="MC-026"]'),button=card.querySelector('[data-publish]');assert.equal(button.disabled,true);card.querySelectorAll('[data-doc]').forEach(c=>{c.checked=true;c.dispatchEvent(new x.w.Event('change',{bubbles:true}))});assert.equal(button.disabled,false);x.click('[data-publish="MC-026"]');assert.match(x.w.sessionStorage.getItem('meken-admin-deals'),/"stage":"live"/);x.dom.window.close()});
test('separate admin login rejects a wrong password and creates a session for the correct one',()=>{const dom=new JSDOM(fs.readFileSync(path.join(site,'admin-login.html'),'utf8'),{url:'http://localhost/admin-login.html',runScripts:'outside-only',virtualConsole:new VirtualConsole()}),w=dom.window,d=w.document;w.eval(fs.readFileSync(path.join(site,'admin-login.js'),'utf8'));d.querySelector('#login-password').value='wrong-pass';d.querySelector('#admin-login').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('#login-error').hidden,false);d.querySelector('#login-password').value='Meken2026!';d.querySelector('#admin-login').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.sessionStorage.getItem('meken-admin-auth'),'ok');dom.window.close()});
